/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(ArrayList<Pedido> p, ArrayList<Pessoa> c, ArrayList<Produto> pro) {
        initComponents();
        cadPed = p;
        cadCliVend = c;
        cadProd = pro;
        modtblProduto = (DefaultTableModel) tblProduto.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrFormaPagamento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        btnConsultarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        jPanelForma = new javax.swing.JPanel();
        rdbVista = new javax.swing.JRadioButton();
        rdbPrazo = new javax.swing.JRadioButton();
        jPanelCliente = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        btnConsultarCliente = new javax.swing.JButton();
        txtCPFCliente = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanelItemProduto = new javax.swing.JPanel();
        lblItemPedido = new javax.swing.JLabel();
        btnConsultarItemPedido = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtdeVendida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblQtdeItens = new javax.swing.JLabel();
        btnRemItem = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        jPanelVendedor = new javax.swing.JPanel();
        lblVendedor = new javax.swing.JLabel();
        btnConsultarVendedor = new javax.swing.JButton();
        txtCPFVendedor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        btnIncluirPedido = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnAlterarPedido = new javax.swing.JButton();
        btnExcluiPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Pedido")));

        jLabel1.setText("Número do Pedido");

        btnConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setEnabled(false);
        txtData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataFocusLost(evt);
            }
        });

        jPanelForma.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        btgrFormaPagamento.add(rdbVista);
        rdbVista.setSelected(true);
        rdbVista.setText("A vista");
        rdbVista.setEnabled(false);

        btgrFormaPagamento.add(rdbPrazo);
        rdbPrazo.setText("A Prazo");
        rdbPrazo.setEnabled(false);

        javax.swing.GroupLayout jPanelFormaLayout = new javax.swing.GroupLayout(jPanelForma);
        jPanelForma.setLayout(jPanelFormaLayout);
        jPanelFormaLayout.setHorizontalGroup(
            jPanelFormaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbVista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdbPrazo)
                .addContainerGap())
        );
        jPanelFormaLayout.setVerticalGroup(
            jPanelFormaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelFormaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbVista)
                    .addComponent(rdbPrazo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarPedido)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanelForma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnConsultarPedido)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelForma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        lblCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        try {
            txtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCliente.setEnabled(false);

        jLabel4.setText("CPF Cliente");

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnConsultarCliente)
                .addGap(18, 18, 18)
                .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelItemProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Item do Produto"));

        lblItemPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultarItemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarItemPedido.setEnabled(false);
        btnConsultarItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItemPedidoActionPerformed(evt);
            }
        });

        jLabel5.setText("Código do Produto");

        txtCodigoProduto.setEnabled(false);

        jLabel7.setText("Qtde. Vendida");

        txtQtdeVendida.setEnabled(false);

        jLabel8.setText("Valor total do Pedido");

        jLabel9.setText("Quantidade de Itens Pedido");

        lblValorTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblQtdeItens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnRemItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnRemItem.setText("Remover Item");
        btnRemItem.setEnabled(false);
        btnRemItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemItemActionPerformed(evt);
            }
        });

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAddItem.setText("Adicionar Item");
        btnAddItem.setEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit", "Qtde.Vend.", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout jPanelItemProdutoLayout = new javax.swing.GroupLayout(jPanelItemProduto);
        jPanelItemProduto.setLayout(jPanelItemProdutoLayout);
        jPanelItemProdutoLayout.setHorizontalGroup(
            jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnConsultarItemPedido)
                        .addGap(25, 25, 25)
                        .addComponent(lblItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItemProdutoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblQtdeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                                        .addComponent(btnAddItem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRemItem)))))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        jPanelItemProdutoLayout.setVerticalGroup(
            jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConsultarItemPedido)
                        .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnRemItem))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanelItemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lblQtdeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        lblVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnConsultarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        try {
            txtCPFVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFVendedor.setEnabled(false);

        jLabel6.setText("CPF Vendedor");

        javax.swing.GroupLayout jPanelVendedorLayout = new javax.swing.GroupLayout(jPanelVendedor);
        jPanelVendedor.setLayout(jPanelVendedorLayout);
        jPanelVendedorLayout.setHorizontalGroup(
            jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConsultarVendedor)
                .addGap(18, 18, 18)
                .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVendedorLayout.setVerticalGroup(
            jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnIncluirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnIncluirPedido.setText("Incluir");
        btnIncluirPedido.setEnabled(false);
        btnIncluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirPedidoActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnAlterarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterarPedido.setText("Alterar");
        btnAlterarPedido.setEnabled(false);
        btnAlterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPedidoActionPerformed(evt);
            }
        });

        btnExcluiPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluiPedido.setText("Excluir");
        btnExcluiPedido.setEnabled(false);
        btnExcluiPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelItemProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVendedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluirPedido)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarPedido)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluiPedido)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelItemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnAlterarPedido)
                    .addComponent(btnExcluiPedido)
                    .addComponent(btnIncluirPedido))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPedidoActionPerformed
        int x;
        String aux = "";
        ArrayList<ItemPedido> itens = cadPed.get(posPed).getItemPedido();;

        for (int i = 0; i < cadPed.get(posPed).getItemPedido().size(); i++) {
            cadPed.get(posPed).getItemPedido().removeAll(itens);
        }

        for (int i = 0; i < modtblProduto.getRowCount(); i++) {
            for (x = 0; x < cadProd.size(); x++) {
                if (cadProd.get(x) instanceof Produto) {
                    if (((Produto) cadProd.get(x)).getCodigo().equals(String.valueOf(modtblProduto.getValueAt(i, 0)))) {
                        break;
                    }
                }
            }
            aux = String.valueOf(modtblProduto.getValueAt(i, 3));
            aux = aux.replace(',', '.');
            ItemPedido objItem = new ItemPedido(i,
                    Double.parseDouble(aux),
                    cadProd.get(x));
            objPedido.addItemPedido(objItem);
        }

        txtNumPedido.setText(null);
        txtData.setText(null);
        txtCPFCliente.setText(null);
        lblCliente.setText(null);
        txtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtCodigoProduto.setText(null);
        lblItemPedido.setText(null);
        txtQtdeVendida.setText(null);
        lblValorTotal.setText(null);
        lblQtdeItens.setText(null);
        modtblProduto.setNumRows(0);
        txtData.setEnabled(false);
        btnAlterarPedido.setEnabled(false);
        btnExcluiPedido.setEnabled(false);
        rdbVista.setSelected(true);
        txtNumPedido.setEnabled(true);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodigoProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
        btnIncluirPedido.setEnabled(false);
        btnConsultarPedido.setEnabled(true);
        btnAddItem.setEnabled(false);
        btnRemItem.setEnabled(false);
        txtNumPedido.requestFocus();

    }//GEN-LAST:event_btnAlterarPedidoActionPerformed

    private void btnExcluiPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiPedidoActionPerformed
        if (posPed >= 0) {
            cadPed.remove(posPed);
            posPed = -1;
        }
        txtNumPedido.setText(null);
        txtData.setText(null);

        txtCPFCliente.setText(null);
        lblCliente.setText(null);
        txtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtCodigoProduto.setText(null);
        lblItemPedido.setText(null);
        txtQtdeVendida.setText(null);
        lblValorTotal.setText(null);
        lblQtdeItens.setText(null);
        modtblProduto.setNumRows(0);
        txtData.setEnabled(false);
        btnAlterarPedido.setEnabled(false);
        btnExcluiPedido.setEnabled(false);
        rdbVista.setSelected(true);
        txtNumPedido.setEnabled(true);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodigoProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
        btnIncluirPedido.setEnabled(false);
        btnConsultarPedido.setEnabled(true);
        btnAddItem.setEnabled(false);
        btnRemItem.setEnabled(false);
        txtNumPedido.requestFocus();
    }//GEN-LAST:event_btnExcluiPedidoActionPerformed

    private void btnConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidoActionPerformed
        int x, itens;
        String aux = "";
        double valorPedido = 0.0;
        for (x = 0; x < cadPed.size(); x++) {
            if (cadPed.get(x) instanceof Pedido) {
                if (((Pedido) cadPed.get(x)).getNumero().equals(txtNumPedido.getText())) {
                    break;
                }
            }
        }

        if (x < cadPed.size()) {
            posPed = x;
        } else {
            posPed = -1;
        }

        if (posPed >= 0) {
            txtData.setText(cadPed.get(posPed).getDataEmissao());
            //btgrFormaPagamento.setSelected(btgrFormaPagamento, cadPed.get(posPed).getFormaPagto());
            rdbPrazo.setSelected(cadPed.get(posPed).getFormaPagto());
            txtCPFCliente.setText(cadPed.get(posPed).getCliente().getCpf());
            lblCliente.setText(cadPed.get(posPed).getCliente().getNome());
            txtCPFVendedor.setText(cadPed.get(posPed).getVendedor().getCpf());
            lblVendedor.setText(cadPed.get(posPed).getVendedor().getNome());
            if (cadPed.get(posPed).getFormaPagto()) {
                rdbVista.setSelected(true);
            } else {
                rdbPrazo.setSelected(true);
            }

            btnConsultarItemPedido.setEnabled(true);

            itens = cadPed.get(posPed).getItemPedido().size();
            for (int i = 0; i < itens; i++) {
                String linhas[] = {cadPed.get(posPed).getItemPedido().get(i).getProduto().getCodigo(),
                    cadPed.get(posPed).getItemPedido().get(i).getProduto().getDescricao(),
                    String.valueOf(cadPed.get(posPed).getItemPedido().get(i).getProduto().getPreco()),
                    String.valueOf(cadPed.get(posPed).getItemPedido().get(i).getQntdVendida()),
                    String.valueOf(cadPed.get(posPed).getItemPedido().get(i).getQntdVendida() * cadPed.get(posPed).getItemPedido().get(i).getProduto().getPreco())};
                modtblProduto.addRow(linhas);
            }

            for (int i = 0; i < modtblProduto.getRowCount(); i++) {
                aux = String.valueOf(modtblProduto.getValueAt(i, 4));
                aux = aux.replace(',', '.');
                valorPedido += Double.parseDouble(aux);
            }

            lblValorTotal.setText(String.valueOf(valorPedido));
            lblQtdeItens.setText(String.valueOf(modtblProduto.getRowCount()));
            txtNumPedido.setEnabled(false);
            btnConsultarPedido.setEnabled(false);
            btnAddItem.setEnabled(true);
            btnRemItem.setEnabled(true);
            btnAlterarPedido.setEnabled(true);
            btnExcluiPedido.setEnabled(true);
            txtCodigoProduto.setEnabled(true);
        } else {
            txtData.setEnabled(true);
            rdbPrazo.setEnabled(true);
            rdbVista.setEnabled(true);
            btnConsultarPedido.setEnabled(false);
            btnConsultarCliente.setEnabled(true);

            txtData.requestFocus();
        }

    }//GEN-LAST:event_btnConsultarPedidoActionPerformed

    private void txtDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataFocusLost
        if (Pedido.validaData(txtData.getText())) {
            objPedido = new Pedido(txtNumPedido.getText(),
                    txtData.getText());

            txtData.setEnabled(false);
            txtCPFCliente.setEnabled(true);
            btnConsultarCliente.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Data Inválida!",
                    "Data",
                    JOptionPane.WARNING_MESSAGE);
            txtData.setText(null);
            txtData.requestFocus();
        }
    }//GEN-LAST:event_txtDataFocusLost

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        int x;
        for (x = 0; x < cadCliVend.size(); x++) {
            if (cadCliVend.get(x) instanceof Cliente) {
                if (((Cliente) cadCliVend.get(x)).getCpf().equals(txtCPFCliente.getText())) {
                    break;
                }
            }
        }

        if (x < cadCliVend.size()) {
            posCliVenPro = x;
        } else {
            posCliVenPro = -1;
        }

        if (posCliVenPro >= 0) {
            ((Cliente) cadCliVend.get(posCliVenPro)).addPedido(objPedido);
            lblCliente.setText(cadCliVend.get(posCliVenPro).getNome());

            txtCPFVendedor.setEnabled(true);
            btnConsultarVendedor.setEnabled(true);
            txtCPFCliente.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Cliente Não Cadastrado!",
                    "Cliente Inválido",
                    JOptionPane.WARNING_MESSAGE);
            txtCPFCliente.setText(null);
            txtCPFCliente.requestFocus();
        }


    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        int x;
        for (x = 0; x < cadCliVend.size(); x++) {
            if (cadCliVend.get(x) instanceof Vendedor) {
                if (((Vendedor) cadCliVend.get(x)).getCpf().equals(txtCPFVendedor.getText())) {
                    break;
                }
            }
        }

        if (x < cadCliVend.size()) {
            posCliVenPro = x;
        } else {
            posCliVenPro = -1;
        }

        if (posCliVenPro >= 0) {
            ((Vendedor) cadCliVend.get(posCliVenPro)).addPedido(objPedido);
            lblVendedor.setText(cadCliVend.get(posCliVenPro).getNome());

            txtCodigoProduto.setEnabled(true);
            btnConsultarItemPedido.setEnabled(true);
            txtCPFVendedor.setEnabled(false);
            btnConsultarVendedor.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Vendedor Não Cadastrado!",
                    "Vendedor Inválido",
                    JOptionPane.WARNING_MESSAGE);
            txtCPFVendedor.setText(null);
            txtCPFVendedor.requestFocus();
        }

    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnConsultarItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItemPedidoActionPerformed
        int x;
        for (x = 0; x < cadProd.size(); x++) {
            if (cadProd.get(x) instanceof Produto) {
                if (((Produto) cadProd.get(x)).getCodigo().equals(txtCodigoProduto.getText())) {
                    break;
                }
            }
        }

        if (x < cadProd.size()) {
            posCliVenPro = x;
        } else {
            posCliVenPro = -1;
        }

        if (posCliVenPro >= 0) {

            lblItemPedido.setText(cadProd.get(posCliVenPro).getDescricao());
            txtQtdeVendida.setEnabled(true);
            btnAddItem.setEnabled(true);
            btnRemItem.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Produto Não Cadastrado!",
                    "Produto Inválido",
                    JOptionPane.WARNING_MESSAGE);
            txtCodigoProduto.setText(null);
            txtCodigoProduto.requestFocus();
        }
    }//GEN-LAST:event_btnConsultarItemPedidoActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if (Double.parseDouble(txtQtdeVendida.getText()) > 0 && (!txtQtdeVendida.getText().isEmpty())) {
            if (cadProd.get(posCliVenPro).getQtdeEstoque() >= Double.parseDouble(txtQtdeVendida.getText())) {
                ItemPedido objItem = new ItemPedido(modtblProduto.getRowCount(), Double.parseDouble(txtQtdeVendida.getText()), cadProd.get(posCliVenPro));
                DecimalFormat Formato = new DecimalFormat("#0.0");
                String aux = "";
                double total = (Double.parseDouble(txtQtdeVendida.getText()) * cadProd.get(posCliVenPro).getPreco());;
                double valorPedido = 0.0, qtdVendida = 0.0;
                int x;
                for (x = 0; x < cadCliVend.size(); x++) {
                    if (cadCliVend.get(x) instanceof Cliente) {
                        if (((Cliente) cadCliVend.get(x)).getCpf().equals(txtCPFCliente.getText())) {
                            break;
                        }
                    }
                }

                if (((Cliente) cadCliVend.get(x)).getLimiteDisp() >= total) {
                    objPedido.addItemPedido(objItem);

                    String linha[] = {cadProd.get(posCliVenPro).getCodigo(),
                        cadProd.get(posCliVenPro).getDescricao(),
                        String.valueOf(cadProd.get(posCliVenPro).getPreco())};

                    modtblProduto.addRow(linha);
                    modtblProduto.setValueAt(Formato.format(Double.parseDouble(txtQtdeVendida.getText())), modtblProduto.getRowCount() - 1, 3);
                    modtblProduto.setValueAt(Formato.format(total), modtblProduto.getRowCount() - 1, 4);

                    for (int i = 0; i < modtblProduto.getRowCount(); i++) {
                        aux = String.valueOf(modtblProduto.getValueAt(i, 4));
                        aux = aux.replace(',', '.');
                        valorPedido += Double.parseDouble(aux);
                    }

                    lblValorTotal.setText(String.valueOf(valorPedido));
                    lblQtdeItens.setText(String.valueOf(modtblProduto.getRowCount()));
                    if (!btnAlterarPedido.isEnabled()) {
                        btnIncluirPedido.setEnabled(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null,
                            "Limite Disponivel Insuficiente!",
                            "Limite Disponivel",
                            JOptionPane.WARNING_MESSAGE);
                    txtQtdeVendida.setText(null);
                    txtQtdeVendida.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(null,
                        "Estoque Insuficiente!",
                        "Estoque",
                        JOptionPane.WARNING_MESSAGE);
                txtQtdeVendida.setText(null);
                txtQtdeVendida.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Quantidade precisa ser Maior que 0!",
                    "Quantidade Inválida",
                    JOptionPane.WARNING_MESSAGE);
            txtQtdeVendida.setText(null);
            txtQtdeVendida.requestFocus();
        }

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRemItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemItemActionPerformed
        String aux = "";
        int x;
        double valorPedido = 0.0;
        if (tblProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "A linha não foi selecionada", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {

            modtblProduto.removeRow(tblProduto.getSelectedRow());
            for (int i = 0; i < modtblProduto.getRowCount(); i++) {
                aux = String.valueOf(modtblProduto.getValueAt(i, 4));
                aux = aux.replace(',', '.');
                valorPedido += Double.parseDouble(aux);
            }

            lblValorTotal.setText(String.valueOf(valorPedido));
            lblQtdeItens.setText(String.valueOf(modtblProduto.getRowCount()));
        }
    }//GEN-LAST:event_btnRemItemActionPerformed

    private void btnIncluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirPedidoActionPerformed
        if (rdbVista.isSelected()) {
            objPedido.setFormaPagto(true);
        } else {
            objPedido.setFormaPagto(false);
        }

        cadPed.add(objPedido);

        txtNumPedido.setText(null);
        txtData.setText(null);
        //radiobutton
        txtCPFCliente.setText(null);
        lblCliente.setText(null);
        txtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtCodigoProduto.setText(null);
        lblItemPedido.setText(null);
        txtQtdeVendida.setText(null);
        lblValorTotal.setText(null);
        lblQtdeItens.setText(null);
        modtblProduto.setNumRows(0);
        rdbVista.setSelected(true);
        txtData.setEnabled(false);
        //  .setEnabled(true);
        txtCPFCliente.setEnabled(false);
        txtCPFVendedor.setEnabled(false);
        txtCodigoProduto.setEnabled(false);
        txtQtdeVendida.setEnabled(false);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
        btnIncluirPedido.setEnabled(false);
        btnConsultarPedido.setEnabled(true);
        btnAddItem.setEnabled(false);
        btnRemItem.setEnabled(false);
        rdbPrazo.setEnabled(false);
        rdbVista.setEnabled(false);
        txtNumPedido.requestFocus();
    }//GEN-LAST:event_btnIncluirPedidoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrFormaPagamento;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAlterarPedido;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarItemPedido;
    private javax.swing.JButton btnConsultarPedido;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluiPedido;
    private javax.swing.JButton btnIncluirPedido;
    private javax.swing.JButton btnRemItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JPanel jPanelForma;
    private javax.swing.JPanel jPanelItemProduto;
    private javax.swing.JPanel jPanelVendedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblItemPedido;
    private javax.swing.JLabel lblQtdeItens;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JRadioButton rdbPrazo;
    private javax.swing.JRadioButton rdbVista;
    private javax.swing.JTable tblProduto;
    private javax.swing.JFormattedTextField txtCPFCliente;
    private javax.swing.JFormattedTextField txtCPFVendedor;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtNumPedido;
    private javax.swing.JTextField txtQtdeVendida;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pedido> cadPed;
    private ArrayList<Pessoa> cadCliVend;
    private ArrayList<Produto> cadProd;
    private Pedido objPedido;
    private int posCliVenPro;
    private int posPed;
    private DefaultTableModel modtblProduto;
}
